-- Migrate existing projects from projects-data.js to Supabase
-- Run this SQL in your Supabase SQL Editor: https://supabase.com/dashboard/project/iraexyvraqmzqzglopph/sql

-- First, check if you want to clear existing data (uncomment to use):
-- TRUNCATE TABLE projects CASCADE;

-- Insert all projects from projects-data.js
INSERT INTO projects (
  title,
  description,
  image,
  technologies,
  roles,
  github,
  demo,
  featured,
  confidential,
  macos_window,
  classification,
  development_status,
  development_timeline,
  display_order,
  active
) VALUES
(
  'Spexop-UI',
  'Complete React component ecosystem with 60+ components, type-safe design tokens, and WCAG AA+ accessibility. MIT licensed with provider-free architecture and modern development practices.',
  'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&h=250&fit=crop',
  ARRAY['React', 'TypeScript', 'Design System', 'Accessibility', 'CLI Tools'],
  ARRAY[]::TEXT[],
  'https://github.com/spexop-ui',
  'https://spexop.com',
  true,
  false,
  true,
  NULL,
  NULL,
  NULL,
  1,
  true
),
(
  'Spexop Pro',
  'Enterprise design system platform for multiple frameworks with advanced component builder, AI-powered theming, MCP integration, and Spexop Command Centre. Complete design-to-code workflow with premium components and enterprise features.',
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop',
  ARRAY['React', 'AI/ML', 'MCP', 'Enterprise', 'Design Tools', 'Command Centre'],
  ARRAY[]::TEXT[],
  'https://github.com/spexop-pro/spexop-pro',
  NULL,
  true,
  false,
  true,
  NULL,
  'Under Development',
  'Q2 2026',
  2,
  true
),
(
  'Argus Eyes Intelligence Platform',
  'Full-stack Signal Intelligence web application featuring advanced SIGINT Command Centre with real-time threat detection, secure communications, and comprehensive surveillance dashboard. Developed both the core intelligence platform and the responsive web interface for authorized agencies.',
  'https://images.unsplash.com/photo-1551808525-51a94da548ce?w=400&h=250&fit=crop',
  ARRAY['Web Development', 'SIGINT', 'Command Centre', 'Real-time Analytics', 'Secure Communications', 'Dashboard UI'],
  ARRAY['Signal Intelligence App Developer', 'Web Application Developer', 'Command Centre Architect'],
  NULL,
  NULL,
  true,
  true,
  true,
  'Military/Intelligence',
  NULL,
  NULL,
  3,
  true
),
(
  'Juno Enterprise Security SDK',
  'Military-grade Software Development Kit for intelligence and enterprise applications. Features advanced authentication systems, Role-Based Access Control (RBAC), end-to-end encrypted communications, comprehensive monitoring and auditing capabilities, and secure vault system for sensitive data management.',
  'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&h=250&fit=crop',
  ARRAY['SDK Development', 'Military Security', 'RBAC', 'Encryption', 'Vault Systems', 'Enterprise Auth', 'Monitoring', 'Auditing'],
  ARRAY['SDK Architect & Developer', 'Security Systems Engineer', 'Enterprise Solutions Developer'],
  NULL,
  NULL,
  true,
  true,
  true,
  'Military/Intelligence',
  NULL,
  NULL,
  4,
  true
),
(
  'IRIS - OSINT Intelligence Plugin',
  'Advanced Open Source Intelligence (OSINT) plugin for Juno SDK providing comprehensive data collection, analysis, and threat assessment capabilities. Features automated social media monitoring, dark web intelligence gathering, and real-time threat correlation for military and intelligence operations.',
  'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
  ARRAY['OSINT Frameworks', 'Data Mining', 'Social Media APIs', 'Threat Intelligence', 'Machine Learning', 'Natural Language Processing', 'Juno SDK', 'Intelligence Analysis'],
  ARRAY['OSINT Analyst', 'Intelligence Software Engineer', 'Threat Assessment Specialist'],
  NULL,
  NULL,
  true,
  true,
  true,
  'Military/Intelligence',
  'Classified Development',
  'Ongoing',
  5,
  true
),
(
  'Interceptor Simulator',
  'Research-grade IMSI/IMEI Catcher simulation platform for telecommunications interception studies. Features advanced environmental configuration including weather conditions, signal disturbors, interference modeling, temporal variations, and density analysis for comprehensive interception scenario testing.',
  'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=250&fit=crop',
  ARRAY['IMSI Catcher', 'IMEI Interception', 'RF Simulation', 'Environmental Modeling', 'Signal Processing', 'Research Platform', 'Telecommunications', 'Interference Analysis'],
  ARRAY['Telecommunications Research Engineer', 'RF Systems Developer', 'Interception Technology Specialist'],
  NULL,
  NULL,
  true,
  true,
  true,
  'Military/Intelligence',
  NULL,
  NULL,
  6,
  true
),
(
  'Atlas - Defense Industry Platform',
  'Comprehensive Django-based web application for managing defense industry products, companies, contacts, and collaboration. Centralized platform organizing military and defense-related equipment, systems, and services with real-time features, asynchronous processing, and advanced data management capabilities.',
  'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop',
  ARRAY['Django 5.1.1', 'Django Channels 3.0.5', 'Celery 5.4.0', 'Redis 5.2.1', 'PostgreSQL', 'Bootstrap 5', 'JavaScript', 'WebSocket', 'HTMX'],
  ARRAY['Full Stack Developer', 'Defense Systems Architect', 'Platform Engineer'],
  NULL,
  NULL,
  true,
  false,
  true,
  'Military/Intelligence',
  'Active Development',
  'Ongoing',
  7,
  true
),
(
  'UniFeeds University News Crawler',
  'Intelligent web crawler system for synchronizing news and announcements from multiple university web pages. Features automated content extraction, duplicate detection, real-time updates, and unified feed aggregation for seamless university communication management.',
  'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400&h=250&fit=crop',
  ARRAY['Web Crawling', 'Data Synchronization', 'Content Extraction', 'University Systems', 'Feed Aggregation', 'Automation', 'Real-time Updates', 'News Processing'],
  ARRAY['Web Scraping Engineer', 'Data Integration Specialist', 'University Systems Developer'],
  NULL,
  NULL,
  false,
  false,
  true,
  NULL,
  NULL,
  NULL,
  8,
  true
),
(
  'Gokturk Alphabet Converter',
  'Specialized linguistic application for game developers to transform modern Latin alphabet Turkish text into ancient runic Gökturk alphabet script. Features accurate historical character mapping, batch text conversion, and seamless integration for creating authentic Turkish gaming experiences with historical authenticity.',
  'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=250&fit=crop',
  ARRAY['Linguistic Programming', 'Character Mapping', 'Turkish Language', 'Game Development Tools', 'Historical Scripts', 'Text Processing', 'Cultural Preservation', 'Developer SDK'],
  ARRAY['Linguistic Software Engineer', 'Game Development Tool Creator', 'Cultural Technology Specialist'],
  NULL,
  'https://gokturk.spexop.de',
  false,
  false,
  true,
  NULL,
  NULL,
  NULL,
  9,
  true
),
(
  'OKX-TR Bot Configurator',
  'Advanced Python Flask application for automated trading bot configuration and optimization. Features comprehensive historical data analysis, technical indicator evaluation, market trend assessment, and intelligent recommendation engine to suggest optimal bot parameters for cryptocurrency trading strategies.',
  'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=250&fit=crop',
  ARRAY['Python', 'Flask', 'Technical Analysis', 'Trading Algorithms', 'Data Analytics', 'Financial APIs', 'Machine Learning', 'Cryptocurrency', 'Bot Configuration'],
  ARRAY['Trading Bot Developer', 'Financial Data Analyst', 'Algorithm Engineer'],
  NULL,
  NULL,
  true,
  false,
  true,
  NULL,
  NULL,
  NULL,
  10,
  true
);

-- Verify the inserts
SELECT 
  id,
  title,
  display_order,
  featured,
  active,
  created_at
FROM projects
ORDER BY display_order;

